version: '3.9'

services:
  jundia-web:
    image: node:alpine
    container_name: jundia-web
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true

